spring:
  application:
    name: promo-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8084

kafka:
  bootstrap-servers : localhost:9092
#  security-protocol: "SASL_PLAINTEXT"
#  sasl-jaasConfig:
#  saslMechanism: SCRAM-SHA-256
  client-id: promo-producer
  topics.promo: promo-topic
  producer:
    acks: all
    retries: 3
    retry-backoff-ms-config: 1000
    request-timeout-ms-config: 15000
    key-serializer-class-config: org.apache.kafka.common.serialization.StringSerializer
    value-serializer-class-config: com.kas.promoservice.util.serializer.PromoEventSerializer


mongo:
  server: mongodb://localhost:27017

server:
  port: 8085
